package com.cs540.curlgen.builder;

import com.cs540.curlgen.exceptions.InvalidUrlFormatException;
import com.cs540.curlgen.models.CurlCommand;

/**
 * The abstract CurlCommand Builder exposes methods to generate the curl command and ensures the necessary methods are implemented by subclasses
 */
public abstract class CurlCommandBuilder implements ICurlCommandBuilder {

    protected CurlCommand curlCommand;

    public CurlCommandBuilder() {
        this.curlCommand = new CurlCommand();
    }

    /**
     * @return String: The curl command generated by the inputs
     */
    public String GenerateCommand() {
        return this.curlCommand.getCurlCommand();
    }


    public abstract void buildHeaders();

    public abstract void buildOptions();

    public abstract void buildUrl() throws InvalidUrlFormatException;

}
